export enum PrExemptionOtherProvider {
  TIMESHARE = 'TIMESHARE',
  FRACTIONAL_OWNERSHIP = 'FRACTIONAL_OWNERSHIP',
  HOME_EXCHANGE = 'HOME_EXCHANGE',
  LODGE_OPERATOR = 'LODGE_OPERATOR',
  EDUCATIONAL_INSTITUTION = 'EDUCATIONAL_INSTITUTION',
  STRATA_GUEST_SUITE = 'STRATA_GUEST_SUITE'
}
