export enum FilingHistoryEventName {
    APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
    INVOICE_GENERATED = 'INVOICE_GENERATED',
    PAYMENT_COMPLETE = 'PAYMENT_COMPLETE',
    PENDING_AUTO_APPROVAL_PROCESSING = 'PENDING_AUTO_APPROVAL_PROCESSING',
    AUTO_APPROVAL_FULL_REVIEW = 'AUTO_APPROVAL_FULL_REVIEW',
    AUTO_APPROVAL_PROVISIONAL = 'AUTO_APPROVAL_PROVISIONAL',
    AUTO_APPROVAL_APPROVED = 'AUTO_APPROVAL_APPROVED',
    FULL_REVIEW_IN_PROGRESS = 'FULL_REVIEW_IN_PROGRESS',
    MANUALLY_APPROVED = 'MANUALLY_APPROVED',
    MANUALLY_DENIED = 'MANUALLY_DENIED',
    MORE_INFORMATION_REQUESTED = 'MORE_INFORMATION_REQUESTED',
    REGISTRATION_CREATED = 'REGISTRATION_CREATED',
    CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
    REGISTRATION_EXPIRED = 'REGISTRATION_EXPIRED',
    NON_COMPLIANCE_SUSPENDED = 'NON_COMPLIANCE_SUSPENDED',
    REGISTRATION_CANCELLED = 'REGISTRATION_CANCELLED',
    APPLICATION_REVIEWER_ASSIGNED = 'APPLICATION_REVIEWER_ASSIGNED',
    APPLICATION_REVIEWER_UNASSIGNED = 'APPLICATION_REVIEWER_UNASSIGNED'
}

export enum FilingHistoryEventType {
    APPLICATION = 'APPLICATION',
    REGISTRATION = 'REGISTRATION',
    USER = 'USER'
}
