export enum RegistrationStatusE {
  SUBMITTED = 'SUBMITTED',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MORE_INFO_NEEDED = 'MORE_INFO_NEEDED',
  APPROVED = 'APPROVED',
  ISSUED = 'ISSUED',
  REJECTED = 'REJECTED',
  DENIED = 'DENIED'
}
