export enum RegistrationStatusE {
  DENIED = 'DENIED',
  APPROVED = 'APPROVED',
  ISSUED = 'ISSUED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MORE_INFO_NEEDED = 'MORE_INFO_NEEDED',
  SUBMITTED = 'SUBMITTED'
}
