export enum ApplicationStatus {
  ADDITIONAL_INFO_REQUESTED = 'ADDITIONAL_INFO_REQUESTED',
  AUTO_APPROVED = 'AUTO_APPROVED',
  DECLINED = 'DECLINED',
  DRAFT = 'DRAFT',
  FULL_REVIEW = 'FULL_REVIEW',
  FULL_REVIEW_APPROVED = 'FULL_REVIEW_APPROVED',
  PAID = 'PAID',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PROVISIONAL = 'PROVISIONAL',
  PROVISIONAL_REVIEW = 'PROVISIONAL_REVIEW',
  PROVISIONALLY_APPROVED = 'PROVISIONALLY_APPROVED'
}
