"""empty message

Revision ID: 49835bc90da3
Revises: 64243bf62473
Create Date: 2024-08-02 06:08:45.172315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49835bc90da3'
down_revision = '64243bf62473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issued_date', sa.DateTime(), server_default=sa.text('(NOW())'), nullable=False))
        batch_op.add_column(sa.Column('issuer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['issuer_id'], ['id'])
        batch_op.drop_column('creation_date')
        batch_op.drop_column('expiry_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', postgresql.TIMESTAMP(), server_default=sa.text("(now() + '1 year'::interval)"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('issuer_id')
        batch_op.drop_column('issued_date')
    # ### end Alembic commands ###
