"""empty message

Revision ID: 8c8a9bfdfbfa
Revises: 1ddad4ce0e21
Create Date: 2024-11-04 06:13:43.557091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c8a9bfdfbfa'
down_revision = '1ddad4ce0e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strata_hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_name', sa.String(length=250), nullable=False),
    sa.Column('home_jurisdiction', sa.String(length=150), nullable=False),
    sa.Column('business_number', sa.String(length=150), nullable=True),
    sa.Column('attorney_name', sa.String(length=250), nullable=True),
    sa.Column('brand_name', sa.String(length=250), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('mailing_address_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('registered_office_attorney_mailing_address_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotels_created_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['addresses.id'], name=op.f('fk_strata_hotels_location_id_addresses')),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], name=op.f('fk_strata_hotels_mailing_address_id_addresses')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotels_modified_by_id_users')),
    sa.ForeignKeyConstraint(['registered_office_attorney_mailing_address_id'], ['addresses.id'], name=op.f('fk_strata_hotels_registered_office_attorney_mailing_address_id_addresses')),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('strata_hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strata_hotels_legal_name'), ['legal_name'], unique=False)

    op.create_table('strata_hotels_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('legal_name', sa.String(length=250), autoincrement=False, nullable=False),
    sa.Column('home_jurisdiction', sa.String(length=150), autoincrement=False, nullable=False),
    sa.Column('business_number', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('attorney_name', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.String(length=250), autoincrement=False, nullable=False),
    sa.Column('website', sa.String(length=1000), autoincrement=False, nullable=False),
    sa.Column('number_of_units', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('mailing_address_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('registered_office_attorney_mailing_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotels_created_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['addresses.id'], name=op.f('fk_strata_hotels_location_id_addresses')),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], name=op.f('fk_strata_hotels_mailing_address_id_addresses')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotels_modified_by_id_users')),
    sa.ForeignKeyConstraint(['registered_office_attorney_mailing_address_id'], ['addresses.id'], name=op.f('fk_strata_hotels_registered_office_attorney_mailing_address_id_addresses')),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('strata_hotels_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strata_hotels_history_legal_name'), ['legal_name'], unique=False)

    op.create_table('strata_hotel_buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('strata_hotel_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_strata_hotel_buildings_address_id_addresses')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotel_buildings_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotel_buildings_modified_by_id_users')),
    sa.ForeignKeyConstraint(['strata_hotel_id'], ['strata_hotels.id'], name=op.f('fk_strata_hotel_buildings_strata_hotel_id_strata_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('strata_hotel_buildings_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('strata_hotel_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_strata_hotel_buildings_address_id_addresses')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotel_buildings_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotel_buildings_modified_by_id_users')),
    sa.ForeignKeyConstraint(['strata_hotel_id'], ['strata_hotels.id'], name=op.f('fk_strata_hotel_buildings_strata_hotel_id_strata_hotels')),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    op.create_table('strata_hotel_registration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('strata_hotel_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotel_registration_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotel_registration_modified_by_id_users')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_strata_hotel_registration_registration_id_registrations')),
    sa.ForeignKeyConstraint(['strata_hotel_id'], ['strata_hotels.id'], name=op.f('fk_strata_hotel_registration_strata_hotel_id_strata_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('strata_hotel_registration_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('registration_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('strata_hotel_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotel_registration_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotel_registration_modified_by_id_users')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_strata_hotel_registration_registration_id_registrations')),
    sa.ForeignKeyConstraint(['strata_hotel_id'], ['strata_hotels.id'], name=op.f('fk_strata_hotel_registration_strata_hotel_id_strata_hotels')),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    op.create_table('strata_hotel_representatives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('strata_hotel_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_strata_hotel_representatives_contact_id_contacts')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotel_representatives_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotel_representatives_modified_by_id_users')),
    sa.ForeignKeyConstraint(['strata_hotel_id'], ['strata_hotels.id'], name=op.f('fk_strata_hotel_representatives_strata_hotel_id_strata_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('strata_hotel_representatives_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('strata_hotel_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_strata_hotel_representatives_contact_id_contacts')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_strata_hotel_representatives_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_strata_hotel_representatives_modified_by_id_users')),
    sa.ForeignKeyConstraint(['strata_hotel_id'], ['strata_hotels.id'], name=op.f('fk_strata_hotel_representatives_strata_hotel_id_strata_hotels')),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strata_hotel_representatives_history')
    op.drop_table('strata_hotel_representatives')
    op.drop_table('strata_hotel_registration_history')
    op.drop_table('strata_hotel_registration')
    op.drop_table('strata_hotel_buildings_history')
    op.drop_table('strata_hotel_buildings')
    with op.batch_alter_table('strata_hotels_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strata_hotels_history_legal_name'))

    op.drop_table('strata_hotels_history')
    with op.batch_alter_table('strata_hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strata_hotels_legal_name'))

    op.drop_table('strata_hotels')
    # ### end Alembic commands ###
