"""empty message

Revision ID: bb586f56f51a
Revises: a07c418dc065
Create Date: 2024-11-18 05:30:42.690465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb586f56f51a'
down_revision = 'a07c418dc065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    registrationtype = postgresql.ENUM('HOST', 'PLATFORM', 'STRATA_HOTEL', name='registrationtype')
    registrationtype.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_type', registrationtype, nullable=True))
        batch_op.create_index(batch_op.f('ix_application_registration_type'), ['registration_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_registration_type'))
        batch_op.drop_column('registration_type')
    # ### end Alembic commands ###
