"""empty message

Revision ID: af12e6e13e47
Revises: c8d5441975d9
Create Date: 2024-09-27 16:57:05.264881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af12e6e13e47'
down_revision = 'c8d5441975d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'registrations', ['registration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('registration_id')
    # ### end Alembic commands ###
