"""empty message

Revision ID: 0fb49e0b4707
Revises: 8912b6965de6
Create Date: 2024-12-12 06:11:20.394557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb49e0b4707'
down_revision = '8912b6965de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('contacts_history', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts_history', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
