"""empty message

Revision ID: fbfe24b319e0
Revises: 3fea78720cd0
Create Date: 2025-07-25 19:17:04.687516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbfe24b319e0'
down_revision = '3fea78720cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('parsing_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)

    with op.batch_alter_table('documents_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parsing_error', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_history_document_type'), ['document_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_history_document_type'))
        batch_op.drop_column('parsing_error')
        batch_op.drop_column('parsed_data')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_column('parsing_error')
        batch_op.drop_column('parsed_data')

    # ### end Alembic commands ###
