"""empty message

Revision ID: d13ee8332cf2
Revises: 0246484e3738
Create Date: 2025-09-24 15:33:16.109748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd13ee8332cf2'
down_revision = '0246484e3738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    rentalspaceoption = postgresql.ENUM('DIFFERENT_PROPERTY', 'SEPARATE_UNIT_SAME_PROPERTY', 'PRIMARY_RESIDENCE_OR_SHARED_SPACE', name='rentalspaceoption')
    rentalspaceoption.create(op.get_bind(), checkfirst=True)

    hosttype = postgresql.ENUM('OWNER', 'FRIEND_RELATIVE', 'LONG_TERM_TENANT', name='hosttype')
    hosttype.create(op.get_bind(), checkfirst=True)

    # Existing ENUM type
    rentalunitspacetype = postgresql.ENUM('ENTIRE_HOME', 'SHARED_ACCOMMODATION', name='rentalunitspacetype', create_type=False)
    ownershiptype = postgresql.ENUM('OWN', 'RENT', 'CO_OWN', 'OTHER', name='ownershiptype', create_type=False)

    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_space_option', sa.Enum('DIFFERENT_PROPERTY', 'SEPARATE_UNIT_SAME_PROPERTY', 'PRIMARY_RESIDENCE_OR_SHARED_SPACE', name='rentalspaceoption'), nullable=True))
        batch_op.add_column(sa.Column('host_type', sa.Enum('OWNER', 'FRIEND_RELATIVE', 'LONG_TERM_TENANT', name='hosttype'), nullable=True))
        batch_op.alter_column('space_type',
               existing_type=rentalunitspacetype,
               nullable=True)
        batch_op.alter_column('ownership_type',
               existing_type=ownershiptype,
               nullable=True)
        batch_op.alter_column('is_unit_on_principal_residence_property',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('number_of_rooms_for_rent',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_space_option', sa.Enum('DIFFERENT_PROPERTY', 'SEPARATE_UNIT_SAME_PROPERTY', 'PRIMARY_RESIDENCE_OR_SHARED_SPACE', name='rentalspaceoption'), nullable=True))
        batch_op.add_column(sa.Column('host_type', sa.Enum('OWNER', 'FRIEND_RELATIVE', 'LONG_TERM_TENANT', name='hosttype'), nullable=True))
        batch_op.alter_column('space_type',
               existing_type=rentalunitspacetype,
               nullable=True)
        batch_op.alter_column('ownership_type',
               existing_type=ownershiptype,
               nullable=True)
        batch_op.alter_column('is_unit_on_principal_residence_property',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('number_of_rooms_for_rent',
               existing_type=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    rentalunitspacetype = postgresql.ENUM('ENTIRE_HOME', 'SHARED_ACCOMMODATION', name='rentalunitspacetype', create_type=False)
    ownershiptype = postgresql.ENUM('OWN', 'RENT', 'CO_OWN', 'OTHER', name='ownershiptype', create_type=False)

    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.alter_column('space_type',
               existing_type=rentalunitspacetype,
               nullable=False)
        batch_op.alter_column('ownership_type',
               existing_type=ownershiptype,
               nullable=False)
        batch_op.alter_column('is_unit_on_principal_residence_property',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('number_of_rooms_for_rent',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.drop_column('host_type')
        batch_op.drop_column('rental_space_option')

    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.alter_column('space_type',
               existing_type=rentalunitspacetype,
               nullable=False)
        batch_op.alter_column('ownership_type',
               existing_type=ownershiptype,
               nullable=False)
        batch_op.alter_column('is_unit_on_principal_residence_property',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('number_of_rooms_for_rent',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.drop_column('host_type')
        batch_op.drop_column('rental_space_option')

    op.execute("DROP TYPE IF EXISTS hosttype;")
    op.execute("DROP TYPE IF EXISTS rentalspaceoption;")

    # ### end Alembic commands ###
