"""empty message

Revision ID: e130ae6339ff
Revises: 96fc8a9c7bc9
Create Date: 2025-05-22 08:37:52.171136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e130ae6339ff'
down_revision = '96fc8a9c7bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('registrations_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_date', sa.DateTime(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations_history', schema=None) as batch_op:
        batch_op.drop_column('cancelled_date')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('cancelled_date')

    # ### end Alembic commands ###
