"""empty message

Revision ID: fa8ce9c9d96c
Revises: 693dbc97236f
Create Date: 2025-07-01 07:38:21.426641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8ce9c9d96c'
down_revision = '693dbc97236f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_notice_of_consideration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_registration_notice_of_consideration_registration_id_registrations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_notice_of_consideration')
    # ### end Alembic commands ###
