"""empty message

Revision ID: eaaf302a8c3f
Revises: b9681cffdca0
Create Date: 2025-01-10 06:50:55.047398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaf302a8c3f'
down_revision = 'b9681cffdca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_validation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_file_id', sa.String(length=250), nullable=True),
    sa.Column('response_file_id', sa.String(length=250), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(), server_default=sa.text('(NOW())'), nullable=False),
    sa.Column('response_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NOT_PROCESSED', 'PROCESSING', 'ERROR', 'COMPLETED', name='status'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_bulk_validation_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_bulk_validation_modified_by_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_validation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_validation_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_validation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_validation_status'))

    op.drop_table('bulk_validation')
    # ### end Alembic commands ###
