"""empty message

Revision ID: 08c4d4a3d80f
Revises: 5bcae325d544
Create Date: 2025-08-06 10:18:51.262768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c4d4a3d80f'
down_revision = '5bcae325d544'
branch_labels = None
depends_on = None

old_options = ('APPLICATION_SUBMITTED', 'INVOICE_GENERATED', 'PAYMENT_COMPLETE', 'PENDING_AUTO_APPROVAL_PROCESSING', 'AUTO_APPROVAL_FULL_REVIEW', 'AUTO_APPROVAL_PROVISIONAL', 'AUTO_APPROVAL_APPROVED', 'FULL_REVIEW_IN_PROGRESS', 'MANUALLY_APPROVED', 'MANUALLY_DENIED', 'MORE_INFORMATION_REQUESTED', 'REGISTRATION_CREATED', 'CERTIFICATE_ISSUED', 'REGISTRATION_EXPIRED', 'NON_COMPLIANCE_SUSPENDED', 'REGISTRATION_CANCELLED', 'APPLICATION_REVIEWER_ASSIGNED', 'APPLICATION_REVIEWER_UNASSIGNED', 'NOC_SENT', 'NOC_EXPIRED', 'HOST_APPLICATION_UNIT_ADDRESS_UPDATED', 'HOST_REGISTRATION_UNIT_ADDRESS_UPDATED', 'APPLICATION_DECISION_SET_ASIDE', 'REGISTRATION_REINSTATED', 'REGISTRATION_DECISION_SET_ASIDE', 'REGISTRATION_DOCUMENT_UPLOADED')
new_options = ('APPLICATION_SUBMITTED', 'INVOICE_GENERATED', 'PAYMENT_COMPLETE', 'PENDING_AUTO_APPROVAL_PROCESSING', 'AUTO_APPROVAL_FULL_REVIEW', 'AUTO_APPROVAL_PROVISIONAL', 'AUTO_APPROVAL_APPROVED', 'FULL_REVIEW_IN_PROGRESS', 'MANUALLY_APPROVED', 'MANUALLY_DENIED', 'MORE_INFORMATION_REQUESTED', 'REGISTRATION_CREATED', 'CERTIFICATE_ISSUED', 'REGISTRATION_EXPIRED', 'NON_COMPLIANCE_SUSPENDED', 'REGISTRATION_CANCELLED', 'APPLICATION_REVIEWER_ASSIGNED', 'APPLICATION_REVIEWER_UNASSIGNED', 'NOC_SENT', 'NOC_EXPIRED', 'HOST_APPLICATION_UNIT_ADDRESS_UPDATED', 'HOST_REGISTRATION_UNIT_ADDRESS_UPDATED', 'APPLICATION_DECISION_SET_ASIDE', 'REGISTRATION_REINSTATED', 'REGISTRATION_DECISION_SET_ASIDE', 'REGISTRATION_DOCUMENT_UPLOADED', 'REGISTRATION_ASSIGNEE_ASSIGNED', 'REGISTRATION_ASSIGNEE_UNASSIGNED')

old_type = sa.Enum(*old_options, name='eventname')
new_type = sa.Enum(*new_options, name='eventname')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE eventname RENAME TO tmp_eventname')
    new_type.create(op.get_bind())
    op.execute('ALTER TABLE events ALTER COLUMN event_name TYPE eventname USING event_name::text::eventname')
    op.execute('DROP TYPE tmp_eventname')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_application_decider_id_users'), 'users', ['decider_id'], ['id'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('decider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_registrations_decider_id_users'), 'users', ['decider_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_registrations_reviewer_id_users'), 'users', ['reviewer_id'], ['id'])

    with op.batch_alter_table('registrations_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('decider_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_registrations_reviewer_id_users'), 'users', ['reviewer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_registrations_decider_id_users'), 'users', ['decider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE eventname RENAME TO tmp_eventname')
    old_type.create(op.get_bind())
    op.execute('ALTER TABLE events ALTER COLUMN event_name TYPE eventname USING event_name::text::eventname')
    op.execute('DROP TYPE tmp_eventname')

    with op.batch_alter_table('registrations_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_registrations_decider_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_registrations_reviewer_id_users'), type_='foreignkey')
        batch_op.drop_column('decider_id')
        batch_op.drop_column('reviewer_id')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_registrations_reviewer_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_registrations_decider_id_users'), type_='foreignkey')
        batch_op.drop_column('decider_id')
        batch_op.drop_column('reviewer_id')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_application_decider_id_users'), type_='foreignkey')
        batch_op.drop_column('decider_id')

    # ### end Alembic commands ###
