"""Add unit_listings column to strata_hotels table.

Revision ID: a9f3c7e8b2d1
Revises: c8f2e3a4b5d6
Create Date: 2025-11-26 07:54:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f3c7e8b2d1'
down_revision = 'c8f2e3a4b5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strata_hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_listings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strata_hotels', schema=None) as batch_op:
        batch_op.drop_column('unit_listings')
    # ### end Alembic commands ###
