"""empty message

Revision ID: 4b8c0e9d2f6a
Revises: 9c8f72d31a5e
Create Date: 2025-03-31 11:32:18.190085

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '4b8c0e9d2f6a'
down_revision = '9c8f72d31a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(
            'idx_gin_application_json_path_ops',
            ['application_json'],
            unique=False,
            postgresql_using='gin',
            postgresql_ops={'application_json': 'jsonb_path_ops'}
        )
        batch_op.create_index(
            'ix_application_application_number',
            ['application_number'],
            unique=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index('ix_application_application_number')
        batch_op.drop_index('idx_gin_application_json_path_ops', postgresql_using='gin')
    # ### end Alembic commands ###
