"""empty message

Revision ID: 5bcae325d544
Revises: fbfe24b319e0
Create Date: 2025-08-07 23:04:19.430603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bcae325d544'
down_revision = 'fbfe24b319e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions_of_approval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preapproved_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('custom_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('minBookingDays', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_conditions_of_approval_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_conditions_of_approval_modified_by_id_users')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_conditions_of_approval_registration_id_registrations')),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('conditions_of_approval_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('preapproved_conditions', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.Column('custom_conditions', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.Column('minBookingDays', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('registration_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_conditions_of_approval_created_by_id_users')),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name=op.f('fk_conditions_of_approval_modified_by_id_users')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_conditions_of_approval_registration_id_registrations')),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conditions_of_approval_history')
    op.drop_table('conditions_of_approval')
    # ### end Alembic commands ###
