"""Add category column to StrataHotel model

Revision ID: 73f39f000110
Revises: 5ac8342c6534
Create Date: 2025-01-28 21:28:15.026837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73f39f000110'
down_revision = '5ac8342c6534'
branch_labels = None
depends_on = None
        
def upgrade():
    stratahotelcategory = postgresql.ENUM('FULL_SERVICE', 'MULTI_UNIT_NON_PR', 'POST_DECEMBER_2023', name='stratahotelcategory')
    stratahotelcategory.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strata_hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('FULL_SERVICE', 'MULTI_UNIT_NON_PR', 'POST_DECEMBER_2023', name='stratahotelcategory'), nullable=True))
        batch_op.create_index(batch_op.f('ix_strata_hotels_category'), ['category'], unique=False)

    with op.batch_alter_table('strata_hotels_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('FULL_SERVICE', 'MULTI_UNIT_NON_PR', 'POST_DECEMBER_2023', name='stratahotelcategory'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_strata_hotels_history_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strata_hotels_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strata_hotels_history_category'))
        batch_op.drop_column('category')

    with op.batch_alter_table('strata_hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strata_hotels_category'))
        batch_op.drop_column('category')

    stratahotelcategory = postgresql.ENUM(name='stratahotelcategory')
    stratahotelcategory.drop(op.get_bind(), checkfirst=True)    

    # ### end Alembic commands ###
