"""empty message

Revision ID: 0246484e3738
Revises: 01af2e30f00f
Create Date: 2025-09-04 05:29:13.666688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0246484e3738'
down_revision = '01af2e30f00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_registration_snapshot_registration_id_registrations')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_snapshot_version'), ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_snapshot_version'))

    op.drop_table('registration_snapshot')
    # ### end Alembic commands ###
