"""empty message

Revision ID: 3fea78720cd0
Revises: fa8ce9c9d96c
Create Date: 2025-07-18 19:35:41.932782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fea78720cd0'
down_revision = 'fa8ce9c9d96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bl_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('jurisdiction', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strr_exempt', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rental_properties_jurisdiction'), ['jurisdiction'], unique=False)

    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr_required', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bl_required', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('jurisdiction', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('strr_exempt', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_rental_properties_history_jurisdiction'), ['jurisdiction'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_properties_history_jurisdiction'))
        batch_op.drop_column('strr_exempt')
        batch_op.drop_column('jurisdiction')
        batch_op.drop_column('bl_required')
        batch_op.drop_column('pr_required')

    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_properties_jurisdiction'))
        batch_op.drop_column('strr_exempt')
        batch_op.drop_column('jurisdiction')
        batch_op.drop_column('bl_required')
        batch_op.drop_column('pr_required')

    # ### end Alembic commands ###
