export enum DocumentUploadType {
  BC_DRIVERS_LICENSE = 'BC_DRIVERS_LICENSE',
  BCSC = 'BCSC',
  COMBINED_BCSC_LICENSE = 'COMBINED_BCSC_LICENSE',
  PROPERTY_ASSESSMENT_NOTICE = 'PROPERTY_ASSESSMENT_NOTICE',
  ICBC_CERTIFICATE_OF_INSURANCE = 'ICBC_CERTIFICATE_OF_INSURANCE',
  HOME_INSURANCE_SUMMARY = 'HOME_INSURANCE_SUMMARY',
  PROPERTY_TAX_NOTICE = 'PROPERTY_TAX_NOTICE',
  GOVT_OR_CROWN_CORP_OFFICIAL_NOTICE = 'GOVT_OR_CROWN_CORP_OFFICIAL_NOTICE',
  FRACTIONAL_OWNERSHIP_AGREEMENT = 'FRACTIONAL_OWNERSHIP_AGREEMENT',
  STRATA_HOTEL_DOCUMENTATION = 'STRATA_HOTEL_DOCUMENTATION',
  TENANCY_AGREEMENT = 'TENANCY_AGREEMENT',
  RENT_RECEIPT_OR_BANK_STATEMENT = 'RENT_RECEIPT_OR_BANK_STATEMENT',
  LOCAL_GOVT_BUSINESS_LICENSE = 'LOCAL_GOVT_BUSINESS_LICENSE',
  OTHERS = 'OTHERS',

  // to be removed
  SPEC_TAX_CONFIRMATION = 'SPEC_TAX_CONFIRMATION',
  HOG_DECLARATION = 'HOG_DECLARATION',
  UTILITY_BILL = 'UTILITY_BILL',

  // new documents
  TITLE_CERTIFICATE_OR_SEARCH = 'TITLE_CERTIFICATE_OR_SEARCH',
  SPECULATION_VACANCY_TAX_DECLARATION = 'SPECULATION_VACANCY_TAX_DECLARATION',
  HOME_OWNER_GRANT_APPROVAL = 'HOME_OWNER_GRANT_APPROVAL',
  NOTARIZED_REAL_ESTATE_DOC = 'NOTARIZED_REAL_ESTATE_DOC',
  PROPERTY_TRANSFER_TAX_RETURN = 'PROPERTY_TRANSFER_TAX_RETURN',
  AFFIDAVIT_PRINCIPAL_RESIDENCE = 'AFFIDAVIT_PRINCIPAL_RESIDENCE',
  ASSESSMENT_ACT_NOTICE = 'ASSESSMENT_ACT_NOTICE',
  MORTGAGE_STATEMENT_OR_SAVINGS_DOC = 'MORTGAGE_STATEMENT_OR_SAVINGS_DOC'
}
