export enum DocumentUploadType {
  BC_DRIVERS_LICENCE = 'BC_DRIVERS_LICENCE',
  BCSC = 'BCSC',
  COMBINED_BCSC_LICENCE = 'COMBINED_BCSC_LICENCE',
  PROPERTY_ASSESSMENT_NOTICE = 'PROPERTY_ASSESSMENT_NOTICE',
  SPEC_TAX_CONFIRMATION = 'SPEC_TAX_CONFIRMATION',
  HOG_DECLARATION = 'HOG_DECLARATION',
  ICBC_CERTIFICATE_OF_INSURANCE = 'ICBC_CERTIFICATE_OF_INSURANCE',
  HOME_INSURANCE_SUMMARY = 'HOME_INSURANCE_SUMMARY',
  PROPERTY_TAX_NOTICE = 'PROPERTY_TAX_NOTICE',
  UTILITY_BILL = 'UTILITY_BILL',
  GOVT_OR_CROWN_CORP_OFFICIAL_NOTICE = 'GOVT_OR_CROWN_CORP_OFFICIAL_NOTICE',
  FRACTIONAL_OWNERSHIP_AGREEMENT = 'FRACTIONAL_OWNERSHIP_AGREEMENT',
  STRATA_HOTEL_DOCUMENTATION = 'STRATA_HOTEL_DOCUMENTATION',
  TENANCY_AGREEMENT = 'TENANCY_AGREEMENT',
  RENT_RECEIPT_OR_BANK_STATEMENT = 'RENT_RECEIPT_OR_BANK_STATEMENT',
  LOCAL_GOVT_BUSINESS_LICENSE = 'LOCAL_GOVT_BUSINESS_LICENSE',
  OTHERS = 'OTHERS'
}
