export enum PropertyType {
  SECONDARY_SUITE = 'SECONDARY_SUITE',
  ACCESSORY_DWELLING = 'ACCESSORY_DWELLING',
  TOWN_HOME = 'TOWN_HOME',
  MULTI_UNIT_HOUSING = 'MULTI_UNIT_HOUSING',
  CONDO_OR_APT = 'CONDO_OR_APT',
  STRATA_HOTEL = 'STRATA_HOTEL',
  SINGLE_FAMILY_HOME = 'SINGLE_FAMILY_HOME',
  RECREATIONAL = 'RECREATIONAL',
  BED_AND_BREAKFAST = 'BED_AND_BREAKFAST',
  FLOAT_HOME = 'FLOAT_HOME'
}

export enum PropertyHostType {
  OWNER = 'OWNER',
  FRIEND_RELATIVE = 'FRIEND_RELATIVE',
  LONG_TERM_TENANT = 'LONG_TERM_TENANT'
}
