"""empty message

Revision ID: 14f84cc80367
Revises: dbca5f95ed31
Create Date: 2024-10-28 16:59:58.471068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14f84cc80367'
down_revision = 'dbca5f95ed31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    hostresidence = postgresql.ENUM('SAME_UNIT', 'ANOTHER_UNIT', name='hostresidence')
    hostresidence.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.alter_column('host_residence',
               existing_type=hostresidence,
               nullable=True)

    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.alter_column('host_residence',
               existing_type=hostresidence,
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    hostresidence = postgresql.ENUM('SAME_UNIT', 'ANOTHER_UNIT', name='hostresidence')
    hostresidence.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.alter_column('host_residence',
               existing_type=hostresidence,
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.alter_column('host_residence',
               existing_type=hostresidence,
               nullable=False)
    # ### end Alembic commands ###
