"""empty message

Revision ID: ac23b69c2c1a
Revises: bfdd00905978
Create Date: 2024-08-01 05:12:55.706629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac23b69c2c1a'
down_revision = 'bfdd00905978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_status_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_account', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name='invoices_registration_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoices_pkey')
    )
    # ### end Alembic commands ###
