"""empty message

Revision ID: a3c9d7aec165
Revises: 7aa7d47cece4
Create Date: 2024-07-24 04:43:45.762425

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3c9d7aec165'
down_revision = '7aa7d47cece4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_approval_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.alter_column('registration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['id'])

    with op.batch_alter_table('ltsa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.alter_column('registration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltsa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('registration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('application_id')

    with op.batch_alter_table('auto_approval_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('registration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('application_id')
    # ### end Alembic commands ###
