"""empty message

Revision ID: 9f1cd9a7258f
Revises: bb586f56f51a
Create Date: 2024-11-22 20:30:42.842000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f1cd9a7258f'
down_revision = 'bb586f56f51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strata_hotel_registration_number', sa.String(), nullable=True))

    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strata_hotel_registration_number', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_properties_history', schema=None) as batch_op:
        batch_op.drop_column('strata_hotel_registration_number')

    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.drop_column('strata_hotel_registration_number')
    # ### end Alembic commands ###
