"""empty message

Revision ID: 8912b6965de6
Revises: 3e8d07a339d5
Create Date: 2024-12-06 07:31:11.272331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8912b6965de6'
down_revision = '3e8d07a339d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    propertymanagertype = postgresql.ENUM('INDIVIDUAL', 'BUSINESS', name='propertymanagertype')
    propertymanagertype.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('property_manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_manager_type', propertymanagertype, nullable=True))
        batch_op.add_column(sa.Column('primary_contact_id', sa.Integer(), nullable=True))
        batch_op.alter_column('business_mailing_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_property_manager_contact_id_contacts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_property_manager_primary_contact_id_contacts'), 'contacts', ['primary_contact_id'], ['id'])
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('property_manager_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_manager_type', propertymanagertype, autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('primary_contact_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.alter_column('business_mailing_address_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.drop_constraint('fk_property_manager_contact_id_contacts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_property_manager_primary_contact_id_contacts'), 'contacts', ['primary_contact_id'], ['id'])
        batch_op.drop_column('contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_manager_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_property_manager_primary_contact_id_contacts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_property_manager_contact_id_contacts', 'contacts', ['contact_id'], ['id'])
        batch_op.alter_column('business_mailing_address_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.drop_column('primary_contact_id')
        batch_op.drop_column('property_manager_type')

    with op.batch_alter_table('property_manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_property_manager_primary_contact_id_contacts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_property_manager_contact_id_contacts', 'contacts', ['contact_id'], ['id'])
        batch_op.alter_column('business_mailing_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('primary_contact_id')
        batch_op.drop_column('property_manager_type')
    # ### end Alembic commands ###
