"""empty message

Revision ID: 2350c2b87dc6
Revises: 9f1cd9a7258f
Create Date: 2024-11-25 02:59:52.444294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2350c2b87dc6'
down_revision = '9f1cd9a7258f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    documenttype = postgresql.ENUM('BC_DRIVERS_LICENSE', 'PROPERTY_ASSESSMENT_NOTICE', 'SPEC_TAX_CONFIRMATION', 'HOG_DECLARATION', 'ICBC_CERTIFICATE_OF_INSURANCE', 'HOME_INSURANCE_SUMMARY', 'PROPERTY_TAX_NOTICE', 'UTILITY_BILL', 'GOVT_OR_CROWN_CORP_OFFICIAL_NOTICE', 'TENANCY_AGREEMENT', 'RENT_RECEIPT_OR_BANK_STATEMENT', 'LOCAL_GOVT_BUSINESS_LICENSE', 'OTHERS', name='documenttype')
    documenttype.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', documenttype, nullable=True))

    with op.batch_alter_table('documents_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', documenttype, autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_history', schema=None) as batch_op:
        batch_op.drop_column('document_type')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('document_type')
    # ### end Alembic commands ###
