"""empty message

Revision ID: a3cf5bb26f36
Revises: a9a4121a8749
Create Date: 2024-10-23 19:13:44.175922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3cf5bb26f36'
down_revision = 'a9a4121a8749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_country_code', sa.String(), nullable=True))

    with op.batch_alter_table('contacts_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_country_code', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts_history', schema=None) as batch_op:
        batch_op.drop_column('phone_country_code')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('phone_country_code')
    # ### end Alembic commands ###
