"""empty message

Revision ID: 730a68e06df1
Revises: 3374a67f7a5a
Create Date: 2024-10-07 02:41:11.111692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '730a68e06df1'
down_revision = '3374a67f7a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_business_licence_expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_properties', schema=None) as batch_op:
        batch_op.drop_column('local_business_licence_expiry_date')
    # ### end Alembic commands ###
