"""empty message

Revision ID: a07c418dc065
Revises: 8c8a9bfdfbfa
Create Date: 2024-11-06 21:10:24.576813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a07c418dc065'
down_revision = '5c6d73a45f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('street_number', sa.String(), nullable=True))

    with op.batch_alter_table('addresses_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_number', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('street_number', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('addresses_history', schema=None) as batch_op:
        batch_op.drop_column('street_number')
        batch_op.drop_column('unit_number')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('street_number')
        batch_op.drop_column('unit_number')

    # ### end Alembic commands ###
